FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev python3-dev build-essential curl && \
    pip install --upgrade pip && \
    pip install patroni[etcd] psycopg[binary] && \
    apt-get remove -y gcc build-essential && apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["patroni"]
