version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_ENABLE_V2=true
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd_data
    networks:
      - patroni_network

  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    volumes:
      - ./patroni1.yml:/etc/patroni.yml
      - postgres1_data:/var/lib/postgresql/data
    depends_on:
      - etcd
    command: >
      /bin/bash -c "
      apt-get update && apt-get install -y python3 python3-pip &&
      pip3 install patroni[etcd] &&
      patroni /etc/patroni.yml
      "
    networks:
      - patroni_network

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    volumes:
      - ./patroni2.yml:/etc/patroni.yml
      - postgres2_data:/var/lib/postgresql/data
    depends_on:
      - etcd
    command: >
      /bin/bash -c "
      apt-get update && apt-get install -y python3 python3-pip &&
      pip3 install patroni[etcd] &&
      patroni /etc/patroni.yml
      "
    networks:
      - patroni_network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "5432:5432"
      - "5000:5000"
    depends_on:
      - postgres1
      - postgres2
    networks:
      - patroni_network

volumes:
  etcd_data:
  postgres1_data:
  postgres2_data:

networks:
  patroni_network:
    driver: bridge
