version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    container_name: etcd
    environment:
      - ETCD_NAME=default
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=default=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_ENABLE_V2=true
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd_data
    networks:
      - patroni_network

  postgres1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    volumes:
      - ./patroni1.yml:/etc/patroni.yml
      - postgres1_data:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      - patroni_network

  postgres2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    volumes:
      - ./patroni2.yml:/etc/patroni.yml
      - postgres2_data:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      - patroni_network
  postgres3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=mydb
    volumes:
      - ./patroni3.yml:/etc/patroni.yml
      - postgres3_data:/var/lib/postgresql/data
    depends_on:
      - etcd
    networks:
      - patroni_network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "5432:5432"  # PostgreSQL Primary
      - "5433:5433"  # PostgreSQL Replica
      - "8005:5000"  # Patroni API (đổi từ 5000 -> 8005)
      - "8404:8404"  # Stats page
    depends_on:
      - postgres1
      - postgres2
      - postgres3
    networks:
      - patroni_network

volumes:
  etcd_data:
  postgres1_data:
  postgres2_data:
  postgres3_data:

networks:
  patroni_network:
    driver: bridge
