scope: postgres
name: postgres3

restapi:
  listen: 0.0.0.0:8008
  connect_address: postgres3:8008

etcd:
  hosts: etcd:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 200
        shared_buffers: 512MB
        work_mem: 16MB
        effective_cache_size: 1536MB
        wal_level: replica
        hot_standby: "on"
        max_replication_slots: 10
        max_wal_senders: 10
  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
    - auth: md5
    - auth-host: md5
    - auth-local: md5
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5
    - host replication replicator 172.22.0.0/16 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: postgres2:5432
  data_dir: /var/lib/postgresql/data
  authentication:
    superuser:
      username: postgres
      password: yourpassword
    replication:
      username: replicator
      password: yourreplicatorpassword
